---
title: House Anxiety
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  releases:
    title: Releases
    output: false
  artists:
    title: Artists
    output: false
  videos:
    title: Videos
    output: false
  uploads:
    title: Uploads
    output: false
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: page
url: http://houseanxiety.co.uk
description: A London-based independent record label, and a proud member of the Marathon Artists family.
permalink: pretty
exclude:
- Gruntfile.js
- Gemfile
- Gemfile.lock
- package.json
- README*
- node_modules
- ".gitignore"
- bower_components
- config.codekit3
- CHANGELOG.md
- LICENSE.md
gems:
- jekyll-seo-tag
- jekyll-sitemap
- jekyll-feed
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
company: House Anxiety
email: info@houseanxietyrecords.co.uk
google_site_verification:
analytics:
logo: "/assets/img/logo.svg"
per_page: 12
date_format: "%Y"
future: true
social:
  facebook: https://www.facebook.com/houseanxietyrecords
  instagram: https://www.instagram.com/houseanxiety/
  twitter: https://twitter.com/houseanxiety